/*
 * ============================================================================
 * COMCAST CONFIDENTIAL AND PROPRIETARY
 * ============================================================================
 * This file and its contents are the intellectual property of Comcast.  It may
 * not be used, copied, distributed or otherwise  disclosed in whole or in part
 * without the express written permission of Comcast.
 * ============================================================================
 * Copyright (c) 2013 Comcast. All rights reserved.
 * ============================================================================
 * This file has been changed from code generated by Grails
 */
import grails.util.Environment;

import java.io.IOException

import com.comcast.rdk.Category;
import com.comcast.rdk.Groups;
import com.comcast.rdk.ScriptFile
import com.comcast.rdk.ScriptGroup
import com.comcast.rdk.TestGroup;
import com.comcast.rdk.User
import com.comcast.rdk.Role
import com.comcast.rdk.Module
import com.comcast.rdk.BoxType
import com.comcast.rdk.BoxManufacturer
import com.comcast.rdk.socketCommuniation.SocketPortConnector

import org.apache.shiro.crypto.hash.Sha256Hash

class BootStrap {
	
	def grailsApplication

    def primitivetestService
	def migrationService
	def scriptService
	def primitiveService
	def executionService
     
	def mailService
	
    def init = { servletContext ->
		
		File layoutFolder = grailsApplication.parentContext.getResource("//fileStore//filetransfer.py").file
		def absolutePath = layoutFolder.absolutePath

		layoutFolder = grailsApplication.parentContext.getResource("//logs//crashlogs//execId_logdata.txt").file
		def absolutePath1 = layoutFolder.absolutePath
		User.withTransaction {
		def user = new User(username: "admin", passwordHash: new Sha256Hash("password").toHex(),
			name : "ADMINISTRATOR", email : "sreelal@tataelxsi.co.in")
        user.addToPermissions("*:*")
        user.save(flush:true)
		}
		createRolesAndAssignForAdmin()

		BoxType.withTransaction {
        def boxTypes = BoxType.list()
        if(!boxTypes){
			def boxtype = new BoxType(name : "IPClient-3", type : "Client", category: Category.RDKV )
			boxtype.save(flush:true)
			boxtype = new BoxType(name : "Hybrid-1", type : "Gateway", category: Category.RDKV)
			boxtype.save(flush:true)
        }
		}
       int port = Integer.parseInt("8089")
        try
        {
           Thread t = new SocketPortConnector(port,absolutePath.toString(),absolutePath1.toString())
           t.start()
        }catch(IOException e)
        {
           e.printStackTrace() 
        }
		
//		migrateScriptGroupContents();
		
		
		if(Environment.current.name == 'production'){
			migrationService.doMigration()
		}
		
		
		/*def sgList = ScriptGroup.list();
		sgList.each { sg ->
			sg.scriptsList.each { script ->
				def mm
				ScriptFile.withTransaction {
					mm = ScriptFile.findByScriptNameAndModuleName(script?.name,script?.primitiveTest?.module?.name)
					if(mm == null){
						mm = new ScriptFile()
						mm.setScriptName(script?.name)
						mm.setModuleName(script?.primitiveTest?.module?.name)
						mm.save()
					}
				}
				if(mm && !sg.scriptList.contains(mm)){
					sg.addToScriptList(mm)
				}

			}
		}*/
		def rootFile = grailsApplication.parentContext.getResource("/")
		scriptService.initializeScriptsData(rootFile.file.getAbsolutePath())
		primitiveService.initializePrimitiveTests(rootFile.file.getAbsolutePath())
//		scriptService?.createSuite()
		executionService.handleInprogressExecutionOnStartup()
		// creates tcl module if it doesn't exist
		createTclModule()
		executionService.tftpServerStartUp(rootFile.file.getAbsolutePath())
		/*List<Script> scriptList = Script.list()
		
		scriptList.each{ scriptInstance ->
			String moduleName = scriptInstance?.primitiveTest?.module?.name
			def scriptGrpInstance = ScriptGroup.findByName(moduleName)
			if(!scriptGrpInstance){
				scriptGrpInstance = new ScriptGroup()
				scriptGrpInstance.name = moduleName
			}
				
			scriptGrpInstance.addToScriptsList(scriptInstance)
			scriptGrpInstance.save(flush:true)
		}*/
		
		//Code to generate the box type & rdk version based script group. Needs to execute once.
		
		/*try {
			List<Script> scriptsList = Script.list()
					
					scriptsList.each{ scriptInstance ->
					
					scriptInstance?.boxTypes?.each{ bType ->
					
					scriptInstance?.rdkVersions?.each{ vers ->
					
					String name = vers?.toString()+"_"+bType?.name
							def scriptGrpInstance = ScriptGroup.findByName(name)
							if(!scriptGrpInstance){
								scriptGrpInstance = new ScriptGroup()
								scriptGrpInstance.name = name
							}
					if(scriptGrpInstance && !scriptGrpInstance?.scriptsList?.contains(scriptInstance)){
						scriptGrpInstance.addToScriptsList(scriptInstance)
						scriptGrpInstance.save(flush:true)
					}
					}
					}
			}
		} catch (Exception e) {
			e.printStackTrace()
		}*/
		
    }
	
	
	def createTclModule() {
		def tclModule = Module.findByName('tcl')
		if(tclModule == null){
			def module = new Module(name : 'tcl', testGroup : TestGroup.Component, groups : null, category: Category.RDKB_TCL )
			if(!module.save(flush:true)){
				module.errors.each{
					println it
				}
			}
		}
	}
	
    
    def destroy = {   
    	if(ExecutionService.tftpProcess != null){
			println " Stopping tftp "
			try {
				ExecutionService.tftpProcess?.destroy()
				ExecutionService.tftpProcess?.exitValue()
			} catch (Exception e) {
				println "ERROR "+ e.getMessage()
				e.printStackTrace()
			}
		}
     
		SocketPortConnector.closeServerSocket()
    }
	
	def createRolesAndAssignForAdmin()
	{
		def permDeviceGroup = "DeviceGroup:*:*"
		def permScriptGroup = "ScriptGroup:*:*"
		def permExecution = "Execution:*:*"
		def permChart = "Trends:*:*"
		def permPrimitiveTest = "PrimitiveTest:*:*"
		def permModule = "Module:*:*"
		def permStreamingDetails = "StreamingDetails:*:*"
		
		
		Role.withTransaction {
		def adminRole = Role.findByName("ADMIN")
		if(!adminRole)
		{
			def adminUser  = User.findByUsername("admin")
			adminRole = new Role(name: "ADMIN")
			adminRole.addToPermissions("*:*")
			adminRole.save(flush:true)
		   
			if(adminUser){
				adminUser.addToRoles(adminRole)
			}
		}
		}
		Role.withTransaction {
		Role testerRole = Role.findByName("TESTER")
		if(!testerRole)
		{
			testerRole = new Role(name: "TESTER")
			testerRole.addToPermissions(permDeviceGroup)
			testerRole.addToPermissions(permScriptGroup)
			testerRole.addToPermissions(permExecution)
			testerRole.addToPermissions(permChart)
			//testerRole.addToPermissions(permPrimitiveTest)
			//testerRole.addToPermissions(permModule)
			//testerRole.addToPermissions(permStreamingDetails)
			
			testerRole.save(flush:true)
		}else{
			if(testerRole.permissions){
				
				if(!testerRole.permissions.contains(permDeviceGroup)){
					testerRole.addToPermissions(permDeviceGroup)
				}
				
				if(!testerRole.permissions.contains(permScriptGroup)){
					testerRole.addToPermissions(permScriptGroup)
				}
				
				if(!testerRole.permissions.contains(permExecution)){
					testerRole.addToPermissions(permExecution)
				}
				
				if(!testerRole.permissions.contains(permChart)){
					testerRole.addToPermissions(permChart)
				}
	
			/*	if(!testerRole.permissions.contains(permPrimitiveTest)){
					testerRole.addToPermissions(permPrimitiveTest)
				}
				
				if(!testerRole.permissions.contains(permModule)){
					testerRole.addToPermissions(permModule)
				}
				
				if(!testerRole.permissions.contains(permStreamingDetails)){
					testerRole.addToPermissions(permStreamingDetails)
				}*/
				
			
				testerRole.save(flush:true)
			}
		}		
		}	
	}

}

              