/*
 * ============================================================================
 * COMCAST CONFIDENTIAL AND PROPRIETARY
 * ============================================================================
 * This file and its contents are the intellectual property of Comcast.  It may
 * not be used, copied, distributed or otherwise  disclosed in whole or in part
 * without the express written permission of Comcast.
 * ============================================================================
 * Copyright (c) 2013 Comcast. All rights reserved.
 * ============================================================================
 * This file has been changed from code generated by Grails
 */
import grails.util.Environment;

import java.io.IOException
import com.comcast.rdk.ScriptGroup
import com.comcast.rdk.Script
import com.comcast.rdk.User
import com.comcast.rdk.Role
import com.comcast.rdk.Module
import com.comcast.rdk.BoxType
import com.comcast.rdk.BoxManufacturer
import com.comcast.rdk.socketCommuniation.SocketPortConnector

import org.apache.shiro.crypto.hash.Sha256Hash

class BootStrap {
	
	def grailsApplication

    def primitivetestService
	def migrationService
     
	def mailService
	
    def init = { servletContext ->
		
		File layoutFolder = grailsApplication.parentContext.getResource("//fileStore//filetransfer.py").file
		def absolutePath = layoutFolder.absolutePath

		layoutFolder = grailsApplication.parentContext.getResource("//logs//crashlogs//execId_logdata.txt").file
		def absolutePath1 = layoutFolder.absolutePath
		User.withTransaction {
		def user = new User(username: "admin", passwordHash: new Sha256Hash("password").toHex(),
			name : "ADMINISTRATOR", email : "sreejasuma@tataelxsi.co.in")
        user.addToPermissions("*:*")
        user.save(flush:true)
		}
		createRolesAndAssignForAdmin()

		BoxType.withTransaction {
        def boxTypes = BoxType.list()
        if(!boxTypes){
			def boxtype = new BoxType(name : "IPClient-3", type : "Client")
			boxtype.save(flush:true)
			boxtype = new BoxType(name : "Hybrid-1", type : "Gateway")
			boxtype.save(flush:true)
        }
		}
       int port = Integer.parseInt("8089")
        try
        {
           Thread t = new SocketPortConnector(port,absolutePath.toString(),absolutePath1.toString())
           t.start()
        }catch(IOException e)
        {
           e.printStackTrace() 
        }
		
		
		migrateScriptGroupContents();
		
		
		if(Environment.current.name == 'production'){
			migrationService.doMigration()
		}
		
		/*List<Script> scriptList = Script.list()
		
		scriptList.each{ scriptInstance ->
			String moduleName = scriptInstance?.primitiveTest?.module?.name
			def scriptGrpInstance = ScriptGroup.findByName(moduleName)
			if(!scriptGrpInstance){
				scriptGrpInstance = new ScriptGroup()
				scriptGrpInstance.name = moduleName
			}
				
			scriptGrpInstance.addToScriptsList(scriptInstance)
			scriptGrpInstance.save(flush:true)
		}*/
		
		//Code to generate the box type & rdk version based script group. Needs to execute once.
		
		/*try {
			List<Script> scriptsList = Script.list()
					
					scriptsList.each{ scriptInstance ->
					
					scriptInstance?.boxTypes?.each{ bType ->
					
					scriptInstance?.rdkVersions?.each{ vers ->
					
					String name = vers?.toString()+"_"+bType?.name
							def scriptGrpInstance = ScriptGroup.findByName(name)
							if(!scriptGrpInstance){
								scriptGrpInstance = new ScriptGroup()
								scriptGrpInstance.name = name
							}
					if(scriptGrpInstance && !scriptGrpInstance?.scriptsList?.contains(scriptInstance)){
						scriptGrpInstance.addToScriptsList(scriptInstance)
						scriptGrpInstance.save(flush:true)
					}
					}
					}
			}
		} catch (Exception e) {
			e.printStackTrace()
		}*/
		
    }
	
	/**
	 * Method to migrate the scripts stored in set(scripts) in script group to list(scriptsList) in script group.
	 * For keeping the order information.
	 * @return
	 */
	def migrateScriptGroupContents(){
		try {
			ScriptGroup.withTransaction {
				def sgList = ScriptGroup.findAll()
				sgList.each { sg ->
					if(sg?.scriptsList == null){
						sg?.scriptsList = []
					}
					def toRemoveList = []
					if(sg?.scripts?.size() > 0 ){
						if(sg?.scriptsList?.size() > 0){
							sg?.scripts?.each{ scrpt ->
								if(!sg?.scriptsList?.contains(scrpt)){
									sg?.scriptsList?.add(scrpt)
								}
								toRemoveList.add(scrpt?.id)
							}
						}else{
							sg?.scriptsList?.addAll(sg?.scripts)
							sg?.scripts?.clear()
						}
					}
					
					if(toRemoveList.size()>0){
						toRemoveList.each { scrptId ->
							Script scrpt = Script.findById(scrptId)
							if(scrpt){
								sg?.scripts?.removeFromScripts(scrpt)
							}
						}
						
					}
				}
			}
		} catch (Exception e) {
			e.printStackTrace()
		}
	}
    
    def destroy = {        
		SocketPortConnector.closeServerSocket()
    }
	
	def createRolesAndAssignForAdmin()
	{
		def permDeviceGroup = "DeviceGroup:*:*"
		def permScriptGroup = "ScriptGroup:*:*"
		def permExecution = "Execution:*:*"
		def permChart = "Trends:*:*"
		def permPrimitiveTest = "PrimitiveTest:*:*"
		def permModule = "Module:*:*"
		def permStreamingDetails = "StreamingDetails:*:*"
		
		
		Role.withTransaction {
		def adminRole = Role.findByName("ADMIN")
		if(!adminRole)
		{
			def adminUser  = User.findByUsername("admin")
			adminRole = new Role(name: "ADMIN")
			adminRole.addToPermissions("*:*")
			adminRole.save(flush:true)
		   
			if(adminUser){
				adminUser.addToRoles(adminRole)
			}
		}
		}
		Role.withTransaction {
		Role testerRole = Role.findByName("TESTER")
		if(!testerRole)
		{
			testerRole = new Role(name: "TESTER")
			testerRole.addToPermissions(permDeviceGroup)
			testerRole.addToPermissions(permScriptGroup)
			testerRole.addToPermissions(permExecution)
			testerRole.addToPermissions(permChart)
			//testerRole.addToPermissions(permPrimitiveTest)
			//testerRole.addToPermissions(permModule)
			//testerRole.addToPermissions(permStreamingDetails)
			
			testerRole.save(flush:true)
		}else{
			if(testerRole.permissions){
				
				if(!testerRole.permissions.contains(permDeviceGroup)){
					testerRole.addToPermissions(permDeviceGroup)
				}
				
				if(!testerRole.permissions.contains(permScriptGroup)){
					testerRole.addToPermissions(permScriptGroup)
				}
				
				if(!testerRole.permissions.contains(permExecution)){
					testerRole.addToPermissions(permExecution)
				}
				
				if(!testerRole.permissions.contains(permChart)){
					testerRole.addToPermissions(permChart)
				}
	
			/*	if(!testerRole.permissions.contains(permPrimitiveTest)){
					testerRole.addToPermissions(permPrimitiveTest)
				}
				
				if(!testerRole.permissions.contains(permModule)){
					testerRole.addToPermissions(permModule)
				}
				
				if(!testerRole.permissions.contains(permStreamingDetails)){
					testerRole.addToPermissions(permStreamingDetails)
				}*/
				
			
				testerRole.save(flush:true)
			}
		}		
		}	
	}

}

              